import { MigrationInterface, QueryRunner } from "typeorm";

export class Migration1777143845368 implements MigrationInterface {
    name = 'Migration1777143845368'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "task_artifacts" DROP CONSTRAINT "FK_task_artifacts_task"`);
        await queryRunner.query(`ALTER TABLE "library_skill_files" DROP CONSTRAINT "FK_library_skill_files_skill"`);
        await queryRunner.query(`ALTER TABLE "project_agents" DROP CONSTRAINT "FK_project_agents_project"`);
        await queryRunner.query(`ALTER TABLE "document_folders" DROP CONSTRAINT "FK_document_folders_user"`);
        await queryRunner.query(`ALTER TABLE "document_folders" DROP CONSTRAINT "FK_document_folders_parent"`);
        await queryRunner.query(`ALTER TABLE "document_folders" DROP CONSTRAINT "FK_document_folders_project"`);
        await queryRunner.query(`ALTER TABLE "document_versions" DROP CONSTRAINT "FK_document_versions_user"`);
        await queryRunner.query(`ALTER TABLE "document_versions" DROP CONSTRAINT "FK_document_versions_document"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP CONSTRAINT "FK_documents_current_version"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP CONSTRAINT "FK_documents_folder"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP CONSTRAINT "FK_documents_user"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP CONSTRAINT "FK_documents_project"`);
        await queryRunner.query(`ALTER TABLE "document_chunks" DROP CONSTRAINT "FK_document_chunks_document"`);
        await queryRunner.query(`ALTER TABLE "workspaces" DROP CONSTRAINT "FK_workspaces_user"`);
        await queryRunner.query(`ALTER TABLE "workspaces" DROP CONSTRAINT "FK_workspaces_project"`);
        await queryRunner.query(`ALTER TABLE "helm_releases" DROP CONSTRAINT "FK_helm_releases_user"`);
        await queryRunner.query(`ALTER TABLE "helm_releases" DROP CONSTRAINT "FK_helm_releases_environment"`);
        await queryRunner.query(`ALTER TABLE "environments" DROP CONSTRAINT "FK_environments_user"`);
        await queryRunner.query(`ALTER TABLE "environments" DROP CONSTRAINT "FK_environments_project"`);
        await queryRunner.query(`ALTER TABLE "document_tags" DROP CONSTRAINT "FK_document_tags_project"`);
        await queryRunner.query(`ALTER TABLE "document_comments" DROP CONSTRAINT "FK_document_comments_parent"`);
        await queryRunner.query(`ALTER TABLE "document_comments" DROP CONSTRAINT "FK_document_comments_user"`);
        await queryRunner.query(`ALTER TABLE "document_comments" DROP CONSTRAINT "FK_document_comments_document"`);
        await queryRunner.query(`ALTER TABLE "document_activities" DROP CONSTRAINT "FK_document_activities_user"`);
        await queryRunner.query(`ALTER TABLE "document_activities" DROP CONSTRAINT "FK_document_activities_document"`);
        await queryRunner.query(`ALTER TABLE "document_templates" DROP CONSTRAINT "FK_document_templates_user"`);
        await queryRunner.query(`ALTER TABLE "document_templates" DROP CONSTRAINT "FK_document_templates_project"`);
        await queryRunner.query(`ALTER TABLE "document_favorites" DROP CONSTRAINT "FK_document_favorites_user"`);
        await queryRunner.query(`ALTER TABLE "document_favorites" DROP CONSTRAINT "FK_document_favorites_document"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_task_artifacts_task_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_library_agents_role"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_library_agents_agent_type"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_library_skill_files_skill_path_active"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_project_agents_project_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_project_agents_library_agent_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_documents_project_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_documents_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_documents_file_type"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_document_chunks_document_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_document_chunks_chunk_index"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_document_chunks_embedding"`);
        await queryRunner.query(`ALTER TABLE "repositories" DROP COLUMN "local_path"`);
        await queryRunner.query(`ALTER TABLE "repositories" DROP COLUMN "source_type"`);
        await queryRunner.query(`ALTER TABLE "repositories" ADD "provider_type" character varying NOT NULL DEFAULT 'git'`);
        await queryRunner.query(`ALTER TABLE "repositories" ADD "bucket_name" character varying`);
        await queryRunner.query(`ALTER TABLE "repositories" ADD "region" character varying`);
        await queryRunner.query(`ALTER TABLE "repositories" ADD "endpoint" character varying`);
        await queryRunner.query(`ALTER TABLE "library_agents" ADD "llm_api_key" text`);
        await queryRunner.query(`ALTER TABLE "task_artifacts" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "task_artifacts" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "task_artifacts" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "task_artifacts" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP COLUMN "agent_profile_id"`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD "agent_profile_id" character varying`);
        await queryRunner.query(`ALTER TABLE "library_skill_files" ALTER COLUMN "content" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "library_skill_files" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "library_skill_files" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "library_skill_files" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "library_skill_files" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "library_skill_files" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "library_skill_files" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "project_agents" DROP COLUMN "library_agent_id"`);
        await queryRunner.query(`ALTER TABLE "project_agents" ADD "library_agent_id" character varying`);
        await queryRunner.query(`ALTER TABLE "document_chunks" DROP COLUMN "embedding"`);
        await queryRunner.query(`ALTER TABLE "document_chunks" ADD "embedding" text`);
        await queryRunner.query(`ALTER TABLE "helm_releases" DROP COLUMN "project_id"`);
        await queryRunner.query(`ALTER TABLE "helm_releases" ADD "project_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "document_comments" ALTER COLUMN "anchor_type" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "task_artifacts" ADD CONSTRAINT "FK_5f215776ae2d2fe83ca4c636c41" FOREIGN KEY ("task_id") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "library_skill_files" ADD CONSTRAINT "FK_76d82de2f591db1b4a26e512585" FOREIGN KEY ("skill_id") REFERENCES "library_skills"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_agents" ADD CONSTRAINT "FK_c04714aa55bbd379f2c4b8347f3" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_folders" ADD CONSTRAINT "FK_6af77f85c3bd6028186a217eff0" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_folders" ADD CONSTRAINT "FK_30db32a329050baf1d013a5714c" FOREIGN KEY ("parent_folder_id") REFERENCES "document_folders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_folders" ADD CONSTRAINT "FK_e10d1bcba475f9258801e0d1d82" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_versions" ADD CONSTRAINT "FK_ac75577bca976d6d581b0f459b6" FOREIGN KEY ("document_id") REFERENCES "documents"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_versions" ADD CONSTRAINT "FK_b2932438efe15477a92ee9aae85" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "documents" ADD CONSTRAINT "FK_e156b298c20873e14c362e789bf" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "documents" ADD CONSTRAINT "FK_e0ccba38ea80d444e2f4614d7cd" FOREIGN KEY ("folder_id") REFERENCES "document_folders"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "documents" ADD CONSTRAINT "FK_a1f222cacfdd65e4b28e7b3c9f6" FOREIGN KEY ("current_version_id") REFERENCES "document_versions"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "documents" ADD CONSTRAINT "FK_b9e28779ec77ff2223e2da41f6d" FOREIGN KEY ("uploaded_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_chunks" ADD CONSTRAINT "FK_b371ff8bc1e4f65fc3d01420be5" FOREIGN KEY ("document_id") REFERENCES "documents"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workspaces" ADD CONSTRAINT "FK_990ebb04c8695df88142b563df8" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workspaces" ADD CONSTRAINT "FK_62422395ad425ffda42e4104056" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "helm_releases" ADD CONSTRAINT "FK_8b158d0dc73cfc6cdd6b6b6a6ce" FOREIGN KEY ("environment_id") REFERENCES "environments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "helm_releases" ADD CONSTRAINT "FK_b2aaa78222c1f336b80b5a41ff7" FOREIGN KEY ("deployed_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "environments" ADD CONSTRAINT "FK_e6abd34366a5d759985d0677616" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "environments" ADD CONSTRAINT "FK_116e9bce4c2372fde31c966af69" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_tags" ADD CONSTRAINT "FK_37d5dc8e6284582402a8ee50187" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_comments" ADD CONSTRAINT "FK_cc25441dacae9903dfb4bd9d15c" FOREIGN KEY ("document_id") REFERENCES "documents"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_comments" ADD CONSTRAINT "FK_d70fdf9bf6c395f48eecb690083" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_comments" ADD CONSTRAINT "FK_d08cce182452717d9ecba3e40dc" FOREIGN KEY ("parent_comment_id") REFERENCES "document_comments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_activities" ADD CONSTRAINT "FK_b939c5e9c26c23a99585fca7869" FOREIGN KEY ("document_id") REFERENCES "documents"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_activities" ADD CONSTRAINT "FK_071c9e0ac5a5456e56d5411ea17" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_templates" ADD CONSTRAINT "FK_49833daafea293ea3e25b41196a" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_templates" ADD CONSTRAINT "FK_2124029cfc6e97d6b467da3a75e" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_favorites" ADD CONSTRAINT "FK_4386025dee9a8f9171e04c1efab" FOREIGN KEY ("document_id") REFERENCES "documents"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_favorites" ADD CONSTRAINT "FK_b1e7ae64bb9b4c077e56b2e53ed" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "document_favorites" DROP CONSTRAINT "FK_b1e7ae64bb9b4c077e56b2e53ed"`);
        await queryRunner.query(`ALTER TABLE "document_favorites" DROP CONSTRAINT "FK_4386025dee9a8f9171e04c1efab"`);
        await queryRunner.query(`ALTER TABLE "document_templates" DROP CONSTRAINT "FK_2124029cfc6e97d6b467da3a75e"`);
        await queryRunner.query(`ALTER TABLE "document_templates" DROP CONSTRAINT "FK_49833daafea293ea3e25b41196a"`);
        await queryRunner.query(`ALTER TABLE "document_activities" DROP CONSTRAINT "FK_071c9e0ac5a5456e56d5411ea17"`);
        await queryRunner.query(`ALTER TABLE "document_activities" DROP CONSTRAINT "FK_b939c5e9c26c23a99585fca7869"`);
        await queryRunner.query(`ALTER TABLE "document_comments" DROP CONSTRAINT "FK_d08cce182452717d9ecba3e40dc"`);
        await queryRunner.query(`ALTER TABLE "document_comments" DROP CONSTRAINT "FK_d70fdf9bf6c395f48eecb690083"`);
        await queryRunner.query(`ALTER TABLE "document_comments" DROP CONSTRAINT "FK_cc25441dacae9903dfb4bd9d15c"`);
        await queryRunner.query(`ALTER TABLE "document_tags" DROP CONSTRAINT "FK_37d5dc8e6284582402a8ee50187"`);
        await queryRunner.query(`ALTER TABLE "environments" DROP CONSTRAINT "FK_116e9bce4c2372fde31c966af69"`);
        await queryRunner.query(`ALTER TABLE "environments" DROP CONSTRAINT "FK_e6abd34366a5d759985d0677616"`);
        await queryRunner.query(`ALTER TABLE "helm_releases" DROP CONSTRAINT "FK_b2aaa78222c1f336b80b5a41ff7"`);
        await queryRunner.query(`ALTER TABLE "helm_releases" DROP CONSTRAINT "FK_8b158d0dc73cfc6cdd6b6b6a6ce"`);
        await queryRunner.query(`ALTER TABLE "workspaces" DROP CONSTRAINT "FK_62422395ad425ffda42e4104056"`);
        await queryRunner.query(`ALTER TABLE "workspaces" DROP CONSTRAINT "FK_990ebb04c8695df88142b563df8"`);
        await queryRunner.query(`ALTER TABLE "document_chunks" DROP CONSTRAINT "FK_b371ff8bc1e4f65fc3d01420be5"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP CONSTRAINT "FK_b9e28779ec77ff2223e2da41f6d"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP CONSTRAINT "FK_a1f222cacfdd65e4b28e7b3c9f6"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP CONSTRAINT "FK_e0ccba38ea80d444e2f4614d7cd"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP CONSTRAINT "FK_e156b298c20873e14c362e789bf"`);
        await queryRunner.query(`ALTER TABLE "document_versions" DROP CONSTRAINT "FK_b2932438efe15477a92ee9aae85"`);
        await queryRunner.query(`ALTER TABLE "document_versions" DROP CONSTRAINT "FK_ac75577bca976d6d581b0f459b6"`);
        await queryRunner.query(`ALTER TABLE "document_folders" DROP CONSTRAINT "FK_e10d1bcba475f9258801e0d1d82"`);
        await queryRunner.query(`ALTER TABLE "document_folders" DROP CONSTRAINT "FK_30db32a329050baf1d013a5714c"`);
        await queryRunner.query(`ALTER TABLE "document_folders" DROP CONSTRAINT "FK_6af77f85c3bd6028186a217eff0"`);
        await queryRunner.query(`ALTER TABLE "project_agents" DROP CONSTRAINT "FK_c04714aa55bbd379f2c4b8347f3"`);
        await queryRunner.query(`ALTER TABLE "library_skill_files" DROP CONSTRAINT "FK_76d82de2f591db1b4a26e512585"`);
        await queryRunner.query(`ALTER TABLE "task_artifacts" DROP CONSTRAINT "FK_5f215776ae2d2fe83ca4c636c41"`);
        await queryRunner.query(`ALTER TABLE "document_comments" ALTER COLUMN "anchor_type" SET DEFAULT 'general'`);
        await queryRunner.query(`ALTER TABLE "helm_releases" DROP COLUMN "project_id"`);
        await queryRunner.query(`ALTER TABLE "helm_releases" ADD "project_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "document_chunks" DROP COLUMN "embedding"`);
        await queryRunner.query(`ALTER TABLE "document_chunks" ADD "embedding" vector(384)`);
        await queryRunner.query(`ALTER TABLE "project_agents" DROP COLUMN "library_agent_id"`);
        await queryRunner.query(`ALTER TABLE "project_agents" ADD "library_agent_id" uuid`);
        await queryRunner.query(`ALTER TABLE "library_skill_files" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "library_skill_files" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "library_skill_files" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "library_skill_files" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "library_skill_files" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "library_skill_files" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "library_skill_files" ALTER COLUMN "content" SET DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP COLUMN "agent_profile_id"`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD "agent_profile_id" uuid`);
        await queryRunner.query(`ALTER TABLE "task_artifacts" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "task_artifacts" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "task_artifacts" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "task_artifacts" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "library_agents" DROP COLUMN "llm_api_key"`);
        await queryRunner.query(`ALTER TABLE "repositories" DROP COLUMN "endpoint"`);
        await queryRunner.query(`ALTER TABLE "repositories" DROP COLUMN "region"`);
        await queryRunner.query(`ALTER TABLE "repositories" DROP COLUMN "bucket_name"`);
        await queryRunner.query(`ALTER TABLE "repositories" DROP COLUMN "provider_type"`);
        await queryRunner.query(`ALTER TABLE "repositories" ADD "source_type" character varying NOT NULL DEFAULT 'remote'`);
        await queryRunner.query(`ALTER TABLE "repositories" ADD "local_path" character varying`);
        await queryRunner.query(`CREATE INDEX "IDX_document_chunks_embedding" ON "document_chunks" ("embedding") `);
        await queryRunner.query(`CREATE INDEX "IDX_document_chunks_chunk_index" ON "document_chunks" ("document_id", "chunk_index") `);
        await queryRunner.query(`CREATE INDEX "IDX_document_chunks_document_id" ON "document_chunks" ("document_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_documents_file_type" ON "documents" ("file_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_documents_status" ON "documents" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_documents_project_id" ON "documents" ("project_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_project_agents_library_agent_id" ON "project_agents" ("library_agent_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_project_agents_project_id" ON "project_agents" ("project_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_library_skill_files_skill_path_active" ON "library_skill_files" ("skill_id", "path") WHERE (deleted_at IS NULL)`);
        await queryRunner.query(`CREATE INDEX "IDX_library_agents_agent_type" ON "library_agents" ("agent_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_library_agents_role" ON "library_agents" ("role") `);
        await queryRunner.query(`CREATE INDEX "IDX_task_artifacts_task_id" ON "task_artifacts" ("task_id") `);
        await queryRunner.query(`ALTER TABLE "document_favorites" ADD CONSTRAINT "FK_document_favorites_document" FOREIGN KEY ("document_id") REFERENCES "documents"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_favorites" ADD CONSTRAINT "FK_document_favorites_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_templates" ADD CONSTRAINT "FK_document_templates_project" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_templates" ADD CONSTRAINT "FK_document_templates_user" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_activities" ADD CONSTRAINT "FK_document_activities_document" FOREIGN KEY ("document_id") REFERENCES "documents"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_activities" ADD CONSTRAINT "FK_document_activities_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_comments" ADD CONSTRAINT "FK_document_comments_document" FOREIGN KEY ("document_id") REFERENCES "documents"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_comments" ADD CONSTRAINT "FK_document_comments_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_comments" ADD CONSTRAINT "FK_document_comments_parent" FOREIGN KEY ("parent_comment_id") REFERENCES "document_comments"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_tags" ADD CONSTRAINT "FK_document_tags_project" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "environments" ADD CONSTRAINT "FK_environments_project" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "environments" ADD CONSTRAINT "FK_environments_user" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "helm_releases" ADD CONSTRAINT "FK_helm_releases_environment" FOREIGN KEY ("environment_id") REFERENCES "environments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "helm_releases" ADD CONSTRAINT "FK_helm_releases_user" FOREIGN KEY ("deployed_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workspaces" ADD CONSTRAINT "FK_workspaces_project" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workspaces" ADD CONSTRAINT "FK_workspaces_user" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_chunks" ADD CONSTRAINT "FK_document_chunks_document" FOREIGN KEY ("document_id") REFERENCES "documents"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "documents" ADD CONSTRAINT "FK_documents_project" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "documents" ADD CONSTRAINT "FK_documents_user" FOREIGN KEY ("uploaded_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "documents" ADD CONSTRAINT "FK_documents_folder" FOREIGN KEY ("folder_id") REFERENCES "document_folders"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "documents" ADD CONSTRAINT "FK_documents_current_version" FOREIGN KEY ("current_version_id") REFERENCES "document_versions"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_versions" ADD CONSTRAINT "FK_document_versions_document" FOREIGN KEY ("document_id") REFERENCES "documents"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_versions" ADD CONSTRAINT "FK_document_versions_user" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_folders" ADD CONSTRAINT "FK_document_folders_project" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_folders" ADD CONSTRAINT "FK_document_folders_parent" FOREIGN KEY ("parent_folder_id") REFERENCES "document_folders"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_folders" ADD CONSTRAINT "FK_document_folders_user" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_agents" ADD CONSTRAINT "FK_project_agents_project" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "library_skill_files" ADD CONSTRAINT "FK_library_skill_files_skill" FOREIGN KEY ("skill_id") REFERENCES "library_skills"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_artifacts" ADD CONSTRAINT "FK_task_artifacts_task" FOREIGN KEY ("task_id") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
