"""add_audit_cols_to_users

Revision ID: 92a813acdb1e
Revises: f0e1d2c3b4a5
Create Date: 2026-05-31 18:17:54.557454+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '92a813acdb1e'
down_revision: str | None = 'f0e1d2c3b4a5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Checkpoint tables are LangGraph-managed and may not exist in all environments
    op.execute("DROP INDEX IF EXISTS checkpoints_thread_id_idx")
    op.execute("DROP TABLE IF EXISTS checkpoints")
    op.execute("DROP INDEX IF EXISTS checkpoint_writes_thread_id_idx")
    op.execute("DROP TABLE IF EXISTS checkpoint_writes")
    op.execute("DROP TABLE IF EXISTS checkpoint_migrations")
    op.execute("DROP INDEX IF EXISTS checkpoint_blobs_thread_id_idx")
    op.execute("DROP TABLE IF EXISTS checkpoint_blobs")
    op.add_column('design_artifacts', sa.Column('deleted_by', sa.String(), nullable=True))
    op.add_column('design_artifacts', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('design_artifacts', sa.Column('updated_by', sa.String(), nullable=True))
    op.add_column('design_artifacts', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('design_messages', sa.Column('deleted_by', sa.String(), nullable=True))
    op.add_column('design_messages', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('design_messages', sa.Column('updated_by', sa.String(), nullable=True))
    op.add_column('design_messages', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('design_sessions', sa.Column('deleted_by', sa.String(), nullable=True))
    op.add_column('design_sessions', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('design_sessions', sa.Column('updated_by', sa.String(), nullable=True))
    op.add_column('document_activities', sa.Column('deleted_by', sa.String(), nullable=True))
    op.add_column('document_activities', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('document_activities', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('document_activities', sa.Column('updated_by', sa.String(), nullable=True))
    op.add_column('document_activities', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('document_chunks', sa.Column('deleted_by', sa.String(), nullable=True))
    op.add_column('document_chunks', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('document_chunks', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('document_chunks', sa.Column('updated_by', sa.String(), nullable=True))
    op.add_column('document_chunks', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('document_comments', sa.Column('deleted_by', sa.String(), nullable=True))
    op.add_column('document_comments', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('document_comments', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('document_comments', sa.Column('updated_by', sa.String(), nullable=True))
    op.add_column('document_folders', sa.Column('creator_id', sa.UUID(), nullable=True))
    op.add_column('document_folders', sa.Column('deleted_by', sa.String(), nullable=True))
    op.add_column('document_folders', sa.Column('updated_by', sa.String(), nullable=True))
    op.drop_constraint(op.f('document_folders_created_by_fkey'), 'document_folders', type_='foreignkey')
    op.alter_column('document_folders', 'created_by',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_foreign_key(None, 'document_folders', 'users', ['creator_id'], ['id'], ondelete='SET NULL')
    op.add_column('document_tags', sa.Column('deleted_by', sa.String(), nullable=True))
    op.add_column('document_tags', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('document_tags', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('document_tags', sa.Column('updated_by', sa.String(), nullable=True))
    op.add_column('document_tags', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('document_templates', sa.Column('creator_id', sa.UUID(), nullable=True))
    op.add_column('document_templates', sa.Column('deleted_by', sa.String(), nullable=True))
    op.add_column('document_templates', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('document_templates', sa.Column('updated_by', sa.String(), nullable=True))
    op.drop_constraint(op.f('document_templates_created_by_fkey'), 'document_templates', type_='foreignkey')
    op.alter_column('document_templates', 'created_by',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_foreign_key(None, 'document_templates', 'users', ['creator_id'], ['id'], ondelete='SET NULL')
    op.add_column('document_versions', sa.Column('creator_id', sa.UUID(), nullable=True))
    op.add_column('document_versions', sa.Column('deleted_by', sa.String(), nullable=True))
    op.add_column('document_versions', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('document_versions', sa.Column('updated_by', sa.String(), nullable=True))
    op.add_column('document_versions', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint(op.f('document_versions_created_by_fkey'), 'document_versions', type_='foreignkey')
    op.alter_column('document_versions', 'created_by',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_foreign_key(None, 'document_versions', 'users', ['creator_id'], ['id'], ondelete='SET NULL')
    op.add_column('documents', sa.Column('deleted_by', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('updated_by', sa.String(), nullable=True))
    op.add_column('environments', sa.Column('creator_id', sa.UUID(), nullable=True))
    op.add_column('environments', sa.Column('deleted_by', sa.String(), nullable=True))
    op.add_column('environments', sa.Column('updated_by', sa.String(), nullable=True))
    op.drop_constraint(op.f('environments_created_by_fkey'), 'environments', type_='foreignkey')
    op.alter_column('environments', 'created_by',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_foreign_key(None, 'environments', 'users', ['creator_id'], ['id'], ondelete='SET NULL')
    op.add_column('helm_releases', sa.Column('deleted_by', sa.String(), nullable=True))
    op.add_column('helm_releases', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('helm_releases', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('helm_releases', sa.Column('updated_by', sa.String(), nullable=True))
    op.add_column('library_agents', sa.Column('deleted_by', sa.String(), nullable=True))
    op.add_column('library_agents', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('library_agents', sa.Column('updated_by', sa.String(), nullable=True))
    op.add_column('library_mcps', sa.Column('deleted_by', sa.String(), nullable=True))
    op.add_column('library_mcps', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('library_mcps', sa.Column('updated_by', sa.String(), nullable=True))
    op.add_column('library_skill_files', sa.Column('deleted_by', sa.String(), nullable=True))
    op.add_column('library_skill_files', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('library_skill_files', sa.Column('updated_by', sa.String(), nullable=True))
    op.add_column('library_skills', sa.Column('deleted_by', sa.String(), nullable=True))
    op.add_column('library_skills', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('library_skills', sa.Column('updated_by', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('deleted_by', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('updated_by', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('plans', sa.Column('deleted_by', sa.String(), nullable=True))
    op.add_column('plans', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('plans', sa.Column('updated_by', sa.String(), nullable=True))
    op.add_column('plans', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('project_agents', sa.Column('deleted_by', sa.String(), nullable=True))
    op.add_column('project_agents', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('project_agents', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('project_agents', sa.Column('updated_by', sa.String(), nullable=True))
    op.alter_column('project_mcps', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_project_mcps_project_id'), table_name='project_mcps')
    op.drop_constraint(op.f('uq_project_mcps_project_slug'), 'project_mcps', type_='unique')
    op.alter_column('project_skills', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_project_skills_project_id'), table_name='project_skills')
    op.drop_constraint(op.f('uq_project_skills_project_slug'), 'project_skills', type_='unique')
    op.add_column('projects', sa.Column('deleted_by', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('updated_by', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('repositories', sa.Column('deleted_by', sa.String(), nullable=True))
    op.add_column('repositories', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('repositories', sa.Column('updated_by', sa.String(), nullable=True))
    op.add_column('repositories', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('settings', sa.Column('deleted_by', sa.String(), nullable=True))
    op.add_column('settings', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('settings', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('settings', sa.Column('updated_by', sa.String(), nullable=True))
    op.add_column('settings', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('settings', 'logo_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('settings', 'favicon_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.add_column('task_artifacts', sa.Column('deleted_by', sa.String(), nullable=True))
    op.add_column('task_artifacts', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('task_artifacts', sa.Column('updated_by', sa.String(), nullable=True))
    op.add_column('task_artifacts', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('tasks', sa.Column('deleted_by', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('updated_by', sa.String(), nullable=True))
    op.add_column('users', sa.Column('deleted_by', sa.String(), nullable=True))
    op.add_column('users', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('users', sa.Column('updated_by', sa.String(), nullable=True))
    op.add_column('workspaces', sa.Column('creator_id', sa.UUID(), nullable=True))
    op.add_column('workspaces', sa.Column('deleted_by', sa.String(), nullable=True))
    op.add_column('workspaces', sa.Column('updated_by', sa.String(), nullable=True))
    op.drop_constraint(op.f('workspaces_created_by_fkey'), 'workspaces', type_='foreignkey')
    op.alter_column('workspaces', 'created_by',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_foreign_key(None, 'workspaces', 'users', ['creator_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workspaces', type_='foreignkey')
    op.create_foreign_key(op.f('workspaces_created_by_fkey'), 'workspaces', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.alter_column('workspaces', 'created_by',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.drop_column('workspaces', 'updated_by')
    op.drop_column('workspaces', 'deleted_by')
    op.drop_column('workspaces', 'creator_id')
    op.drop_column('users', 'updated_by')
    op.drop_column('users', 'created_by')
    op.drop_column('users', 'deleted_by')
    op.drop_column('tasks', 'updated_by')
    op.drop_column('tasks', 'created_by')
    op.drop_column('tasks', 'deleted_by')
    op.drop_column('task_artifacts', 'updated_at')
    op.drop_column('task_artifacts', 'updated_by')
    op.drop_column('task_artifacts', 'created_by')
    op.drop_column('task_artifacts', 'deleted_by')
    op.alter_column('settings', 'favicon_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('settings', 'logo_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('settings', 'created_at')
    op.drop_column('settings', 'updated_by')
    op.drop_column('settings', 'created_by')
    op.drop_column('settings', 'deleted_at')
    op.drop_column('settings', 'deleted_by')
    op.drop_column('repositories', 'created_at')
    op.drop_column('repositories', 'updated_by')
    op.drop_column('repositories', 'created_by')
    op.drop_column('repositories', 'deleted_by')
    op.drop_column('projects', 'updated_at')
    op.drop_column('projects', 'updated_by')
    op.drop_column('projects', 'created_by')
    op.drop_column('projects', 'deleted_by')
    op.create_unique_constraint(op.f('uq_project_skills_project_slug'), 'project_skills', ['project_id', 'slug'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_project_skills_project_id'), 'project_skills', ['project_id'], unique=False)
    op.alter_column('project_skills', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.create_unique_constraint(op.f('uq_project_mcps_project_slug'), 'project_mcps', ['project_id', 'slug'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_project_mcps_project_id'), 'project_mcps', ['project_id'], unique=False)
    op.alter_column('project_mcps', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.drop_column('project_agents', 'updated_by')
    op.drop_column('project_agents', 'created_by')
    op.drop_column('project_agents', 'deleted_at')
    op.drop_column('project_agents', 'deleted_by')
    op.drop_column('plans', 'updated_at')
    op.drop_column('plans', 'updated_by')
    op.drop_column('plans', 'created_by')
    op.drop_column('plans', 'deleted_by')
    op.drop_column('messages', 'updated_at')
    op.drop_column('messages', 'updated_by')
    op.drop_column('messages', 'created_by')
    op.drop_column('messages', 'deleted_by')
    op.drop_column('library_skills', 'updated_by')
    op.drop_column('library_skills', 'created_by')
    op.drop_column('library_skills', 'deleted_by')
    op.drop_column('library_skill_files', 'updated_by')
    op.drop_column('library_skill_files', 'created_by')
    op.drop_column('library_skill_files', 'deleted_by')
    op.drop_column('library_mcps', 'updated_by')
    op.drop_column('library_mcps', 'created_by')
    op.drop_column('library_mcps', 'deleted_by')
    op.drop_column('library_agents', 'updated_by')
    op.drop_column('library_agents', 'created_by')
    op.drop_column('library_agents', 'deleted_by')
    op.drop_column('helm_releases', 'updated_by')
    op.drop_column('helm_releases', 'created_by')
    op.drop_column('helm_releases', 'deleted_at')
    op.drop_column('helm_releases', 'deleted_by')
    op.drop_constraint(None, 'environments', type_='foreignkey')
    op.create_foreign_key(op.f('environments_created_by_fkey'), 'environments', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.alter_column('environments', 'created_by',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.drop_column('environments', 'updated_by')
    op.drop_column('environments', 'deleted_by')
    op.drop_column('environments', 'creator_id')
    op.drop_column('documents', 'updated_by')
    op.drop_column('documents', 'created_by')
    op.drop_column('documents', 'deleted_by')
    op.drop_constraint(None, 'document_versions', type_='foreignkey')
    op.create_foreign_key(op.f('document_versions_created_by_fkey'), 'document_versions', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.alter_column('document_versions', 'created_by',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.drop_column('document_versions', 'updated_at')
    op.drop_column('document_versions', 'updated_by')
    op.drop_column('document_versions', 'deleted_at')
    op.drop_column('document_versions', 'deleted_by')
    op.drop_column('document_versions', 'creator_id')
    op.drop_constraint(None, 'document_templates', type_='foreignkey')
    op.create_foreign_key(op.f('document_templates_created_by_fkey'), 'document_templates', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.alter_column('document_templates', 'created_by',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.drop_column('document_templates', 'updated_by')
    op.drop_column('document_templates', 'deleted_at')
    op.drop_column('document_templates', 'deleted_by')
    op.drop_column('document_templates', 'creator_id')
    op.drop_column('document_tags', 'updated_at')
    op.drop_column('document_tags', 'updated_by')
    op.drop_column('document_tags', 'created_by')
    op.drop_column('document_tags', 'deleted_at')
    op.drop_column('document_tags', 'deleted_by')
    op.drop_constraint(None, 'document_folders', type_='foreignkey')
    op.create_foreign_key(op.f('document_folders_created_by_fkey'), 'document_folders', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.alter_column('document_folders', 'created_by',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.drop_column('document_folders', 'updated_by')
    op.drop_column('document_folders', 'deleted_by')
    op.drop_column('document_folders', 'creator_id')
    op.drop_column('document_comments', 'updated_by')
    op.drop_column('document_comments', 'created_by')
    op.drop_column('document_comments', 'deleted_at')
    op.drop_column('document_comments', 'deleted_by')
    op.drop_column('document_chunks', 'updated_at')
    op.drop_column('document_chunks', 'updated_by')
    op.drop_column('document_chunks', 'created_by')
    op.drop_column('document_chunks', 'deleted_at')
    op.drop_column('document_chunks', 'deleted_by')
    op.drop_column('document_activities', 'updated_at')
    op.drop_column('document_activities', 'updated_by')
    op.drop_column('document_activities', 'created_by')
    op.drop_column('document_activities', 'deleted_at')
    op.drop_column('document_activities', 'deleted_by')
    op.drop_column('design_sessions', 'updated_by')
    op.drop_column('design_sessions', 'created_by')
    op.drop_column('design_sessions', 'deleted_by')
    op.drop_column('design_messages', 'updated_at')
    op.drop_column('design_messages', 'updated_by')
    op.drop_column('design_messages', 'created_by')
    op.drop_column('design_messages', 'deleted_by')
    op.drop_column('design_artifacts', 'updated_at')
    op.drop_column('design_artifacts', 'updated_by')
    op.drop_column('design_artifacts', 'created_by')
    op.drop_column('design_artifacts', 'deleted_by')
    op.create_table('checkpoint_blobs',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('version', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('blob', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'channel', 'version', name=op.f('checkpoint_blobs_pkey'))
    )
    op.create_index(op.f('checkpoint_blobs_thread_id_idx'), 'checkpoint_blobs', ['thread_id'], unique=False)
    op.create_table('checkpoint_migrations',
    sa.Column('v', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('v', name=op.f('checkpoint_migrations_pkey'))
    )
    op.create_table('checkpoint_writes',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('checkpoint_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('idx', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('blob', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('task_path', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', 'task_id', 'idx', name=op.f('checkpoint_writes_pkey'))
    )
    op.create_index(op.f('checkpoint_writes_thread_id_idx'), 'checkpoint_writes', ['thread_id'], unique=False)
    op.create_table('checkpoints',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('checkpoint_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('parent_checkpoint_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('checkpoint', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', name=op.f('checkpoints_pkey'))
    )
    op.create_index(op.f('checkpoints_thread_id_idx'), 'checkpoints', ['thread_id'], unique=False)
    # ### end Alembic commands ###
