"""
telaios.cli.app
---------------
Textual TUI for TelaiOS RAG, planning, and agent execution.

Workflow
--------
  1. Knowledge — scan a folder, analyze structure, ingest into Chroma,
     auto-select best RAG strategy
  2. Plan — agent reviews ingested knowledge, asks clarification questions,
     generates a detailed plan with dependencies
  3. Execute — schedule a team of agents to execute the plan

Layout
------
  Header
  ┌─ Knowledge ──┬─ Plan ──┬─ Execute ──┬─ Activity Log ──────────────┐
  │  Config (left) │ Output log (right)                               │
  └────────────────────────────────────────────────────────────────────┘
  Footer  (q: quit  r: run  Tab: navigate)

Launch
------
  uv run telaios-eval
"""

from __future__ import annotations

import asyncio
import contextlib
import logging
import traceback
from pathlib import Path
from typing import Any, ClassVar

from textual import on, work
from textual.app import App, ComposeResult
from textual.binding import Binding
from textual.containers import Horizontal, Vertical
from textual.css.query import NoMatches
from textual.widgets import (
    Button,
    Footer,
    Header,
    Input,
    Label,
    RichLog,
    Select,
    Static,
    TabbedContent,
    TabPane,
)

from telaios.core.fake_llm import FakeLLM
from telaios.core.knowledge_source import (
    DoclingSource,
    FileSource,
    GitHubSource,
    TextSource,
    URLSource,
)
from telaios.core.knowledge.factory import KnowledgePipelineFactory
from telaios.core.types import (
    AgentInput,
    Message,
    MessageRole,
    RetrievalQuery,
)

logger = logging.getLogger(__name__)

# ── Constants ────────────────────────────────────────────────────────────────

_COLLECTION_NAME = "telaios-tui"
_PLAN_COLLECTION = "telaios-plans"

_SOURCE_TYPES: list[tuple[str, str]] = [
    ("folder", "Local folder (auto-scan)"),
    ("text", "Paste text"),
    ("file", "Single file"),
    ("document", "PDF/DOCX (Docling)"),
    ("url", "Web URL"),
    ("github", "GitHub repo"),
]

_PROFILES: list[tuple[str, str]] = [
    ("hybrid", "Hybrid RAG — HyDE + dense + BM25 + RRF + graph augmentation"),
]

# ── CSS ──────────────────────────────────────────────────────────────────────

CSS = """
Screen {
    background: $surface;
}

#main-tabs {
    height: 1fr;
}

.split {
    height: 1fr;
}

.config-panel {
    width: 40;
    min-width: 36;
    border: solid $primary-darken-2;
    padding: 1 2;
    height: 1fr;
}

.config-panel Label {
    margin-top: 1;
    color: $text-muted;
}

.config-panel Input {
    margin-bottom: 0;
}

.config-panel Select {
    margin-bottom: 0;
}

.desc-block {
    color: $text-muted;
    margin-bottom: 1;
    padding: 0 1;
}

.output-panel {
    border: solid $primary-darken-2;
    height: 1fr;
    padding: 0 1;
}

.run-btn {
    margin-top: 1;
    width: 100%;
}

RichLog {
    height: 1fr;
    scrollbar-gutter: stable;
}

#corpus-stats {
    color: $text-muted;
    padding: 1 0;
}
"""

# ── Plan data model ──────────────────────────────────────────────────────────


class PlanStep:
    """A single step in an execution plan."""

    def __init__(
        self,
        step_id: str,
        title: str,
        description: str,
        agent: str,
        depends_on: list[str] | None = None,
        estimated_tokens: int = 0,
    ) -> None:
        self.step_id = step_id
        self.title = title
        self.description = description
        self.agent = agent
        self.depends_on = depends_on or []
        self.estimated_tokens = estimated_tokens
        self.status = "pending"  # pending | running | done | failed

    def __repr__(self) -> str:
        deps = f" (after {', '.join(self.depends_on)})" if self.depends_on else ""
        return f"[{self.step_id}] {self.title} → {self.agent}{deps}"


class ExecutionPlan:
    """A plan generated by the planning agent."""

    def __init__(self, objective: str = "") -> None:
        self.objective = objective
        self.steps: list[PlanStep] = []
        self.clarification_questions: list[str] = []
        self.clarification_answers: dict[str, str] = {}

    def add_step(self, **kwargs: Any) -> PlanStep:
        step = PlanStep(**kwargs)
        self.steps.append(step)
        return step

    @property
    def ready_steps(self) -> list[PlanStep]:
        """Steps whose dependencies are all done."""
        done_ids = {s.step_id for s in self.steps if s.status == "done"}
        return [
            s
            for s in self.steps
            if s.status == "pending" and all(d in done_ids for d in s.depends_on)
        ]


# ── Pipeline helper ──────────────────────────────────────────────────────────


async def _get_pipeline():
    return await KnowledgePipelineFactory.get()


# ── TUI App ──────────────────────────────────────────────────────────────────


class TelaiOSEval(App[None]):
    """TelaiOS RAG + Planning + Execution TUI."""

    TITLE = "TelaiOS — Knowledge · Plan · Execute"
    CSS = CSS
    BINDINGS: ClassVar = [
        Binding("q", "quit", "Quit"),
        Binding("r", "run", "Run"),
        Binding("ctrl+c", "quit", "Quit", show=False),
    ]

    def __init__(self) -> None:
        super().__init__()
        self._plan: ExecutionPlan | None = None
        self._corpus_stats: dict[str, Any] | None = None
        self._activity_log: list[str] = []

    def _log(self, text: str) -> None:  # type: ignore[override]
        """Append to activity log and push to any visible log widgets."""
        import datetime

        ts = datetime.datetime.now().strftime("%H:%M:%S")
        entry = f"[{ts}] {text}"
        self._activity_log.append(entry)
        # Push to activity log tab if visible
        try:
            log: RichLog = self.query_one("#activity-log", RichLog)
            log.write(entry)
        except NoMatches:
            pass

    # ── Layout ──────────────────────────────────────────────────────────

    def compose(self) -> ComposeResult:
        yield Header(show_clock=True)
        with TabbedContent(id="main-tabs"):
            with TabPane("Knowledge", id="knowledge"):
                yield from self._compose_knowledge_pane()
            with TabPane("Plan", id="plan"):
                yield from self._compose_plan_pane()
            with TabPane("Execute", id="execute"):
                yield from self._compose_execute_pane()
            with TabPane("Activity Log", id="activity_log"):
                yield from self._compose_activity_log_pane()
        yield Footer()

    # ── Knowledge tab ───────────────────────────────────────────────────

    def _compose_knowledge_pane(self) -> ComposeResult:
        yield Static(
            "[bold]1. Knowledge[/bold]\n"
            "Select a folder to scan. The system analyzes file types, estimates "
            "corpus size, and recommends the best RAG strategy.",
            classes="desc-block",
        )
        with Horizontal(classes="split"):
            with Vertical(classes="config-panel"):
                yield Label("Source type")
                yield Select(
                    options=[(label, val) for val, label in _SOURCE_TYPES],
                    value="folder",
                    id="knowledge-source-type",
                )
                yield Label("Folder path / source value")
                yield Input(
                    placeholder="/path/to/docs/  or  paste text / URL / GitHub URL",
                    id="knowledge-source-value",
                )
                yield Label("RAG profile")
                yield Select(
                    options=[(label, val) for val, label in _PROFILES],
                    value="auto",
                    id="knowledge-rag-profile",
                )
                yield Button(
                    "Scan & Ingest [r]", variant="primary", classes="run-btn", id="knowledge-run"
                )
                yield Static("", id="corpus-stats")
            with Vertical(classes="output-panel"):
                yield RichLog(highlight=True, markup=True, id="knowledge-log")

    @on(Select.Changed, "#knowledge-source-type")
    def _on_knowledge_type_changed(self, event: Select.Changed) -> None:
        val = str(event.value)
        try:
            inp: Input = self.query_one("#knowledge-source-value", Input)
        except NoMatches:
            return
        placeholders: dict[str, str] = {
            "folder": "/path/to/docs/  (scans recursively)",
            "text": "Paste your text / code here…",
            "file": "/path/to/file.md",
            "document": "/path/to/report.pdf",
            "url": "https://example.com/article",
            "github": "https://github.com/owner/repo",
        }
        inp.placeholder = placeholders.get(val, inp.placeholder)

    @on(Button.Pressed, "#knowledge-run")
    def _on_knowledge_run(self, event: Button.Pressed) -> None:
        self._dispatch_knowledge_run()

    def _read_knowledge_inputs(self) -> tuple[str, str, str]:
        def _val(wid: str, default: str = "") -> str:
            try:
                w = self.query_one(f"#{wid}")
                if isinstance(w, Input):
                    return w.value or default
                if isinstance(w, Select):
                    v = w.value
                    return str(v) if v is not None else default
            except NoMatches:
                pass
            return default

        return (
            _val("knowledge-source-type", "folder"),
            _val("knowledge-source-value", ""),
            _val("knowledge-rag-profile", "auto"),
        )

    def _dispatch_knowledge_run(self) -> None:
        source_type, source_value, profile = self._read_knowledge_inputs()
        try:
            log: RichLog = self.query_one("#knowledge-log", RichLog)
        except NoMatches:
            return
        log.clear()
        if not source_value.strip():
            log.write("[red]Please enter a source value.[/red]")
            return
        self._run_knowledge_ingest(source_type, source_value, profile, log)

    @work(exclusive=False)
    async def _run_knowledge_ingest(
        self,
        source_type: str,
        source_value: str,
        profile: str,
        log: RichLog,
    ) -> None:
        pipeline = await _get_pipeline()
        project_id = "tui-default"
        self._log(f"Knowledge ingest: type={source_type} value={source_value[:80]}")
        log.write(f"[bold]Scanning [yellow]{source_type}[/yellow]:[/bold] {source_value}")

        try:
            match source_type:
                case "folder":
                    folder = Path(source_value)
                    if not folder.is_dir():  # noqa: ASYNC240
                        log.write("[red]Folder not found: {source_value}[/red]")
                        return
                    files = list(folder.rglob("*"))  # noqa: ASYNC240
                    text_files = [f for f in files if f.is_file() and _is_text_file(f)]
                    doc_files = [f for f in files if f.is_file() and _is_docling_file(f)]
                    log.write("\n[bold]Scan results:[/bold]")
                    log.write(f"  Text files: {len(text_files)}, Documents: {len(doc_files)}")

                    doc_count = 0
                    chunk_count = 0
                    if text_files:
                        source = FileSource(*[str(f) for f in text_files])
                        r = await pipeline.ingest_repository(project_id, source)
                        doc_count += r.document_count
                        chunk_count += r.chunk_count
                    if doc_files:
                        source = DoclingSource(*[str(f) for f in doc_files])
                        r = await pipeline.ingest_documents(project_id, source)
                        doc_count += r.document_count
                        chunk_count += r.chunk_count
                    self._corpus_stats = {"document_count": doc_count, "chunk_count": chunk_count}
                    self._show_corpus_analysis(log, self._corpus_stats)

                case "text":
                    source = TextSource(source_value, title="user-input")
                    r = await pipeline.ingest_documents(project_id, source)
                    self._corpus_stats = {"document_count": r.document_count, "chunk_count": r.chunk_count}
                    self._show_corpus_analysis(log, self._corpus_stats)

                case "file":
                    source = FileSource(source_value)
                    r = await pipeline.ingest_documents(project_id, source)
                    self._corpus_stats = {"document_count": r.document_count, "chunk_count": r.chunk_count}
                    self._show_corpus_analysis(log, self._corpus_stats)

                case "document":
                    source = DoclingSource(source_value)
                    r = await pipeline.ingest_documents(project_id, source)
                    self._corpus_stats = {"document_count": r.document_count, "chunk_count": r.chunk_count}
                    self._show_corpus_analysis(log, self._corpus_stats)

                case "url":
                    source = URLSource(source_value)
                    r = await pipeline.ingest_documents(project_id, source)
                    self._corpus_stats = {"document_count": r.document_count, "chunk_count": r.chunk_count}
                    self._show_corpus_analysis(log, self._corpus_stats)

                case "github":
                    source = GitHubSource(source_value)
                    r = await pipeline.ingest_repository(project_id, source)
                    self._corpus_stats = {"document_count": r.document_count, "chunk_count": r.chunk_count}
                    self._show_corpus_analysis(log, self._corpus_stats)

                case _:
                    log.write(f"[red]Unknown source type: {source_type}[/red]")

        except Exception as exc:
            self._log(f"Ingest error: {exc}")
            logger.exception("Ingest failed")
            log.write(f"[red]Ingest error:[/red] {exc}")
            log.write(f"[dim]{traceback.format_exc()}[/dim]")

    def _show_corpus_analysis(self, log: RichLog, stats: dict[str, Any]) -> None:
        """Show corpus stats after ingestion."""
        doc_count = stats.get("document_count", 0)
        chunk_count = stats.get("chunk_count", 0)

        log.write(f"\n[bold green]Ingested {doc_count} document(s), {chunk_count} chunks[/bold green]")
        log.write("[dim]Pipeline: HyDE → Hybrid (Qdrant + BM25 + RRF) → Graph augmentation[/dim]")

        try:
            stats_label: Static = self.query_one("#corpus-stats", Static)
            stats_label.update(
                f"Corpus: {doc_count} docs, {chunk_count} chunks  [dim](Tab → Plan)[/dim]"
            )
        except NoMatches:
            pass

        self._log(f"Corpus ready: {doc_count} docs, {chunk_count} chunks")
        log.write("\n[dim]Ready — switch to Plan tab to generate a plan.[/dim]")

    # ── Plan tab ────────────────────────────────────────────────────────

    def _compose_plan_pane(self) -> ComposeResult:
        yield Static(
            "[bold]2. Plan[/bold]\n"
            "The planning agent reviews the ingested knowledge, asks clarification "
            "questions if needed, and generates a detailed plan with dependencies.",
            classes="desc-block",
        )
        with Horizontal(classes="split"):
            with Vertical(classes="config-panel"):
                yield Label("Objective")
                yield Input(
                    placeholder="What do you want to build or analyze?",
                    id="plan-objective",
                )
                yield Button(
                    "Generate Plan [r]", variant="primary", classes="run-btn", id="plan-run"
                )
            with Vertical(classes="output-panel"):
                yield RichLog(highlight=True, markup=True, id="plan-log")

    @on(Button.Pressed, "#plan-run")
    def _on_plan_run(self, event: Button.Pressed) -> None:
        self._dispatch_plan_run()

    def _dispatch_plan_run(self) -> None:
        try:
            log: RichLog = self.query_one("#plan-log", RichLog)
        except NoMatches:
            return
        log.clear()
        objective = ""
        with contextlib.suppress(NoMatches):
            objective = self.query_one("#plan-objective", Input).value or ""
        if not objective.strip():
            log.write("[red]Please enter an objective.[/red]")
            return
        self._run_plan_generation(objective, log)

    @work(exclusive=False)
    async def _run_plan_generation(self, objective: str, log: RichLog) -> None:
        self._log(f"Plan generation: objective={objective[:80]}")
        log.write(f"[bold]Planning agent reviewing corpus for:[/bold] {objective}")

        self._get_rag()
        if not self._corpus_stats:
            log.write("[yellow]No corpus ingested yet. Switch to Knowledge tab first.[/yellow]")
            return

        # Step 1: Review corpus
        log.write("\n[bold cyan]── Step 1: Corpus Review ──[/bold cyan]")
        stats = self._corpus_stats
        doc_count = stats.get("document_count", 0)
        types = stats.get("source_types", [])
        code_ratio = stats.get("code_ratio", 0)

        log.write(f"  Documents: {doc_count}")
        log.write(f"  Types: {', '.join(types)}")
        log.write(f"  Code-heavy: {'Yes' if code_ratio > 0.4 else 'No'} ({code_ratio:.0%})")
        await asyncio.sleep(0.3)

        # Step 2: Agent asks clarification questions
        log.write("\n[bold cyan]── Step 2: Clarification Questions ──[/bold cyan]")
        questions = self._generate_clarification_questions(objective, stats)
        if questions:
            for i, q in enumerate(questions, 1):
                log.write(f"  [yellow]Q{i}:[/yellow] {q}")
                await asyncio.sleep(0.2)
            log.write("\n[dim]Using default answers for now (TUI mode).[/dim]")
        else:
            log.write("  [green]No clarification needed — corpus is sufficient.[/green]")
        await asyncio.sleep(0.3)

        # Step 3: Generate plan
        log.write("\n[bold cyan]── Step 3: Plan Generation ──[/bold cyan]")
        plan = self._generate_plan(objective, stats)
        self._plan = plan

        log.write(f"\n[bold]Plan: {plan.objective}[/bold]")
        log.write(f"  Steps: {len(plan.steps)}")
        log.write("")

        for step in plan.steps:
            deps = f" (after {', '.join(step.depends_on)})" if step.depends_on else ""
            log.write(f"  [bold]{step.step_id}[/bold] {step.title}")
            log.write(f"    Agent: {step.agent}")
            log.write(f"    {step.description}")
            if deps:
                log.write(f"    Dependencies:{deps}")
            log.write("")

        log.write("[bold green]Plan ready — switch to Execute tab to run.[/bold green]")
        self._log(f"Plan generated: {len(plan.steps)} steps")

    def _generate_clarification_questions(self, objective: str, stats: dict[str, Any]) -> list[str]:
        """Generate clarification questions based on corpus and objective."""
        questions: list[str] = []
        doc_count = stats.get("document_count", 0)
        types = stats.get("source_types", [])
        code_ratio = stats.get("code_ratio", 0)

        if "code" in types and "text" in types:
            questions.append(
                "The corpus contains both code and documentation. "
                "Should the plan prioritize code analysis or documentation review?"
            )
        if doc_count > 20:
            questions.append(
                f"With {doc_count} documents, should the plan process them "
                "in batches or all at once?"
            )
        if code_ratio > 0.4:
            questions.append(
                "The corpus is code-heavy. Should the agent focus on "
                "architecture analysis, code review, or feature extraction?"
            )
        if "web" in types:
            questions.append(
                "Web content was ingested. Should it be treated as "
                "reference material or primary source?"
            )
        return questions

    def _generate_plan(self, objective: str, stats: dict[str, Any]) -> ExecutionPlan:
        """Generate an execution plan based on objective and corpus."""
        plan = ExecutionPlan(objective=objective)
        types = stats.get("source_types", [])
        code_ratio = stats.get("code_ratio", 0)

        # Phase 1: Analysis
        plan.add_step(
            step_id="A1",
            title="Corpus Analysis",
            description=f"Analyze {stats.get('document_count', 0)} documents "
            f"({', '.join(types)}). Extract key concepts, relationships, and gaps.",
            agent="Analyst Agent",
            depends_on=[],
        )

        # Phase 2: Planning
        plan.add_step(
            step_id="P1",
            title="Architecture Design",
            description="Design system architecture based on corpus analysis. "
            "Identify components, interfaces, and data flow.",
            agent="Architect Agent",
            depends_on=["A1"],
        )

        # Phase 3: Implementation (conditional on code-heavy corpus)
        if code_ratio > 0.3 or "code" in types:
            plan.add_step(
                step_id="I1",
                title="Code Implementation",
                description="Implement core components following the architecture design. "
                "Write tests and documentation.",
                agent="Developer Agent",
                depends_on=["P1"],
            )
            plan.add_step(
                step_id="I2",
                title="Integration & Testing",
                description="Integrate components and run integration tests. "
                "Fix issues and verify functionality.",
                agent="QA Agent",
                depends_on=["I1"],
            )
        else:
            plan.add_step(
                step_id="D1",
                title="Documentation Generation",
                description="Generate structured documentation from corpus analysis. "
                "Include summaries, diagrams, and reference materials.",
                agent="Writer Agent",
                depends_on=["P1"],
            )

        # Phase 4: Review
        plan.add_step(
            step_id="R1",
            title="Final Review",
            description="Review all outputs for accuracy, completeness, and consistency. "
            "Generate final report.",
            agent="Reviewer Agent",
            depends_on=["I2"] if (code_ratio > 0.3 or "code" in types) else ["D1"],
        )

        return plan

    # ── Execute tab ─────────────────────────────────────────────────────

    def _compose_execute_pane(self) -> ComposeResult:
        yield Static(
            "[bold]3. Execute[/bold]\n"
            "Schedule a team of agents to execute the generated plan. "
            "Each step runs when its dependencies are complete.",
            classes="desc-block",
        )
        with Horizontal(classes="split"):
            with Vertical(classes="config-panel"):
                yield Label("Execution mode")
                yield Select(
                    options=[
                        ("Sequential — one step at a time", "sequential"),
                        ("Parallel — run independent steps together", "parallel"),
                    ],
                    value="sequential",
                    id="execute-mode",
                )
                yield Button(
                    "Execute Plan [r]", variant="primary", classes="run-btn", id="execute-run"
                )
            with Vertical(classes="output-panel"):
                yield RichLog(highlight=True, markup=True, id="execute-log")

    @on(Button.Pressed, "#execute-run")
    def _on_execute_run(self, event: Button.Pressed) -> None:
        self._dispatch_execute_run()

    def _dispatch_execute_run(self) -> None:
        try:
            log: RichLog = self.query_one("#execute-log", RichLog)
        except NoMatches:
            return
        log.clear()
        if not self._plan:
            log.write("[red]No plan generated yet. Switch to Plan tab first.[/red]")
            return
        mode = "sequential"
        with contextlib.suppress(NoMatches):
            mode = str(self.query_one("#execute-mode", Select).value)
        self._run_plan_execution(mode, log)

    @work(exclusive=False)
    async def _run_plan_execution(self, mode: str, log: RichLog) -> None:
        self._log(f"Plan execution: mode={mode}")
        plan = self._plan
        if not plan:
            return

        log.write(f"[bold]Executing plan:[/bold] {plan.objective}")
        log.write(f"  Mode: {mode}")
        log.write(f"  Steps: {len(plan.steps)}")
        log.write("")

        llm = FakeLLM()

        completed = 0
        max_iterations = len(plan.steps) * 3  # safety limit
        iteration = 0

        while completed < len(plan.steps) and iteration < max_iterations:
            iteration += 1
            ready = plan.ready_steps
            if not ready:
                log.write("[yellow]No steps ready — possible dependency cycle.[/yellow]")
                break

            if mode == "parallel":
                tasks = [self._execute_step(step, llm, log) for step in ready]
                await asyncio.gather(*tasks)
                completed += len(ready)
            else:
                step = ready[0]
                await self._execute_step(step, llm, log)
                completed += 1

            await asyncio.sleep(0.2)

        # Summary
        log.write(
            f"\n[bold green]Execution complete: {completed}/{len(plan.steps)} steps done[/bold green]"
        )
        for step in plan.steps:
            status_color = {
                "done": "green",
                "failed": "red",
                "running": "yellow",
                "pending": "dim",
            }.get(step.status, "dim")
            log.write(
                f"  [{status_color}]{step.status}[/{status_color}] {step.step_id}: {step.title}"
            )

        self._log(f"Execution complete: {completed}/{len(plan.steps)} steps")

    async def _execute_step(
        self,
        step: PlanStep,
        llm: Any,
        log: RichLog,
    ) -> None:
        """Execute a single plan step using the knowledge pipeline for context."""
        step.status = "running"
        project_id = "tui-default"
        self._log(f"Starting step {step.step_id}: {step.title} (agent={step.agent})")
        log.write(f"\n[bold cyan]── [{step.step_id}] {step.title} ──[/bold cyan]")
        log.write(f"  Agent: {step.agent}")
        log.write(f"  {step.description}")

        pipeline = await _get_pipeline()
        query_text = f"{step.title}: {step.description}"
        result = await pipeline.query(project_id=project_id, text=query_text, top_k=3)

        if result.chunks:
            log.write(f"\n  [dim]Retrieved {len(result.chunks)} relevant chunks:[/dim]")
            for i, chunk in enumerate(result.chunks[:2], 1):
                log.write(f"    [{i}] {chunk.content[:120]}…")

        context = "\n\n".join(c.content for c in result.chunks[:3])
        from langchain_core.messages import HumanMessage, SystemMessage
        response = await llm.ainvoke([
            SystemMessage(content=f"You are a {step.agent}. Use this context:\n{context}"),
            HumanMessage(content=f"Execute this step:\n{step.description}"),
        ])

        log.write(f"\n  [bold green]Output:[/bold green] {response.content[:300]}…")
        step.status = "done"
        self._log(f"Step {step.step_id} completed")

    # ── Activity Log tab ────────────────────────────────────────────────

    def _compose_activity_log_pane(self) -> ComposeResult:
        yield Static(
            "[bold]Activity Log[/bold]\nReal-time log of all actions across all tabs.",
            classes="desc-block",
        )
        with Vertical(classes="output-panel"):
            log = RichLog(highlight=True, markup=True, id="activity-log")
            for entry in self._activity_log:
                log.write(entry)
            yield log


# ── Helpers ──────────────────────────────────────────────────────────────────


def _is_text_file(path: Path) -> bool:
    text_extensions = {
        ".py",
        ".md",
        ".txt",
        ".json",
        ".yaml",
        ".yml",
        ".toml",
        ".cfg",
        ".ini",
        ".env",
        ".sh",
        ".bash",
        ".zsh",
        ".js",
        ".ts",
        ".tsx",
        ".jsx",
        ".css",
        ".html",
        ".htm",
        ".xml",
        ".svg",
        ".csv",
        ".sql",
        ".rst",
        ".tex",
        ".conf",
        ".Makefile",
        ".dockerfile",
    }
    return path.suffix.lower() in text_extensions or path.name.lower() in {
        "makefile",
        "dockerfile",
        "jenkinsfile",
        "vagrantfile",
    }


def _is_docling_file(path: Path) -> bool:
    return path.suffix.lower() in {".pdf", ".docx", ".pptx", ".xlsx"}


# ── Entry point ──────────────────────────────────────────────────────────────


def main() -> None:
    """Launch the TUI. Logs are written to ``tui.log`` in the current directory."""
    from pathlib import Path

    log_file = Path("tui.log")
    logging.basicConfig(
        level=logging.DEBUG,
        format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
        handlers=[
            logging.FileHandler(str(log_file), mode="w"),
            logging.StreamHandler(),
        ],
    )
    logger.info("TUI starting — logs at %s", log_file.absolute())
    TelaiOSEval().run()


if __name__ == "__main__":
    main()
