"""Domain layer — pure Pydantic types, enums, value objects, entities, and contracts.

This layer has zero framework dependencies (no FastAPI, no SQLAlchemy, no
LangChain) and serves as the single source of truth for all domain concepts.

Modules:
- ``enums``      — all ``StrEnum`` types (statuses, roles, categories)
- ``values``     — value objects (typed IDs, Email, DisplayName)
- ``entities``   — pure Pydantic domain entities with business logic
- ``repository`` — ``AbstractRepository[T]`` contract
- ``events``     — domain events and ``EventBus``
"""

from telaios.domain.entities import (
    AgentProfile,
    Document,
    Plan,
    Project,
    ProjectMember,
    Task,
    TaskArtifact,
    User,
    Workspace,
)
from telaios.domain.enums import (
    AgentRole,
    AgentType,
    ArtifactType,
    DesignMessageRole,
    DesignSessionStatus,
    DocumentActivityAction,
    DocumentCommentAnchorType,
    DocumentFileType,
    DocumentStatus,
    EnvironmentStatus,
    EnvironmentType,
    GraphStoreProvider,
    GuardrailAction,
    HelmReleaseStatus,
    K8sResourceKind,
    LLMProvider,
    McpToolPermission,
    McpTransport,
    MessageRole,
    PlanMessageRole,
    PlanningSessionStatus,
    PlanStatus,
    ProjectRole,
    ProjectStatus,
    RagStrategy,
    RepositoryAuthType,
    RepositoryProviderType,
    RepositoryStatus,
    StreamEventType,
    SystemPromptMode,
    SystemRole,
    TaskStatus,
    TaskType,
    WorkspaceStatus,
)
from telaios.domain.events import (
    DomainEvent,
    EventBus,
    MemberAdded,
    MemberRemoved,
    PlanCompleted,
    PlanConfirmed,
    PlanFailed,
    ProjectCreated,
    TaskCompleted,
    TaskCreated,
    TaskFailed,
    TaskStatusChanged,
)
from telaios.domain.repository import AbstractRepository
from telaios.domain.values import (
    AgentProfileId,
    AnnotatedArtifactId,
    AnnotatedCommentId,
    AnnotatedDocumentId,
    AnnotatedEnvironmentId,
    AnnotatedMessageId,
    AnnotatedPlanId,
    AnnotatedProjectId,
    AnnotatedRepositoryId,
    AnnotatedTaskId,
    AnnotatedUserId,
    AnnotatedWorkspaceId,
    ArtifactId,
    CommentId,
    DisplayName,
    DocumentId,
    Email,
    EntityId,
    EnvironmentId,
    MessageId,
    PlanId,
    ProjectId,
    RepositoryId,
    TaskId,
    UserId,
    WorkspaceId,
)

__all__ = [
    "AbstractRepository",
    "AgentProfile",
    "AgentProfileId",
    "AgentRole",
    "AgentType",
    "AnnotatedArtifactId",
    "AnnotatedCommentId",
    "AnnotatedDocumentId",
    "AnnotatedEnvironmentId",
    "AnnotatedMessageId",
    "AnnotatedPlanId",
    "AnnotatedProjectId",
    "AnnotatedRepositoryId",
    "AnnotatedTaskId",
    "AnnotatedUserId",
    "AnnotatedWorkspaceId",
    "ArtifactId",
    "ArtifactType",
    "CommentId",
    "DesignMessageRole",
    "DesignSessionStatus",
    "DisplayName",
    "Document",
    "DocumentActivityAction",
    "DocumentCommentAnchorType",
    "DocumentFileType",
    "DocumentId",
    "DocumentStatus",
    "DomainEvent",
    "Email",
    "EntityId",
    "EnvironmentId",
    "EnvironmentStatus",
    "EnvironmentType",
    "EventBus",
    "GraphStoreProvider",
    "GuardrailAction",
    "HelmReleaseStatus",
    "K8sResourceKind",
    "LLMProvider",
    "McpToolPermission",
    "McpTransport",
    "MemberAdded",
    "MemberRemoved",
    "MessageId",
    "MessageRole",
    "Plan",
    "PlanCompleted",
    "PlanConfirmed",
    "PlanFailed",
    "PlanId",
    "PlanMessageRole",
    "PlanStatus",
    "PlanningSessionStatus",
    "Project",
    "ProjectCreated",
    "ProjectId",
    "ProjectMember",
    "ProjectRole",
    "ProjectStatus",
    "RagStrategy",
    "RepositoryAuthType",
    "RepositoryId",
    "RepositoryProviderType",
    "RepositoryStatus",
    "StreamEventType",
    "SystemPromptMode",
    "SystemRole",
    "Task",
    "TaskArtifact",
    "TaskCompleted",
    "TaskCreated",
    "TaskFailed",
    "TaskId",
    "TaskStatus",
    "TaskStatusChanged",
    "TaskType",
    "User",
    "UserId",
    "Workspace",
    "WorkspaceId",
    "WorkspaceStatus",
]
